Redux setup + чистка папки public.
smashboy/cloud-table pull request #2
Opened 2020-01-26 14:44 UTC by smashboy

2020-01-27 22:46 UTC, Shakhzadov commented on src/Components/Toolbar/Components/GenerateTableForm.js
>    return (
Можна використати перед return деструктор об'єктів --> const { rowsInput, colsInput } = inputState; 
І в рядках 36, 43, 54, 55 чуть скоротити к-ть букв.

2020-01-27 22:59 UTC, Shakhzadov commented on src/redux/Actions/TableActions/generateTableAction.js
> +    });
Цей екшен має виводити якийсь спінер, поки ми чекаємо на завантаження таблиці?

2020-01-27 23:19 UTC, Shakhzadov commented on src/redux/keys.js
> +export const generateTableLoading = "generateTableLoading";
Домовлялись же про одинарні лапки ? Чому ти для ключів і констант вирішив використати подвійні?

2020-01-27 23:27 UTC, Shakhzadov commented on src/redux/reducers/UIReducer.js
> + * UI reducer is needed for separating actual data from UI related data,
Мені не подобається, що один редюсер з великої літери починається (UIReducer) інший з малої (tableReducer). Притримуйся одного стилю (в даному випадку camelCase) --> uiReducer aбо userInterfaceReducer

2020-01-27 23:31 UTC, Shakhzadov commented on src/redux/types/UITypes.js
> +export const CLEAR_LOADING_UI = "CLEAR_LOADING_UI";
Лапки одинарні + в мене питання для чого роз'єднювати константи і ключі по різним файлам і отримувати велику к-ть файлів з малою к-тю даних ? Я б на твоєму місці об'єднював їх по максимуму в один файл. Твоїх коментарів буде достатньо, щоб людина зрозуміла що для чого.

2020-01-27 23:33 UTC, Shakhzadov commented on src/redux/types/tableTypes.js
> +export const SET_CELL_VALUE = "SET_CELL_VALUE";
Лапки одинарні + об'єднай з іншими константами редакса в один файл.

2020-01-27 23:41 UTC, Shakhzadov commented on src/Components/Toolbar/Components/GenerateTableForm.js
>  import React, { useState } from 'react';
Глибина вкладеності файлів надлишкова на мою думку --> src/**Components**/Toolbar/**Components**/GenerateTableForm.js , таких повторень не повинно бути. 
CSS файли не потрібно виносити в окрему папку, а всі компоненти можуть бути на тому ж рівні, що і базовий файл (в твоєму випадку index.js), який бажано називати назвою з файлу (TableView) або перейменовувати в Root (і відповідно перейменовувати).

2020-01-27 23:51 UTC, Shakhzadov requested changes
Глянь на мої зауваження і запитання. В основному там по структурі проекту, бо як на мене ти дуже сильно розносиш дані по окремим файлам. Для конкретного проекту це не критично (бо він невеликий), але для великих проектів це буде надлишково. І константи згрібай в один файл теж, замість 3-4 файлів в 5-10 рядків матимемо 1 в 20-40 і всім пофіг звідки та константа імпортована, якщо в неї читабельна назва. Ще попрошу вставити по пробілу тут (між Rows/Cols і дужкою ) --> Rows (1-500): і по пробілу додай в Календарі Завдань всюди перед відкриваючими дужками, бо мені очі муляє. А в загальному все добре, код читабельний і структурований. Молодець.

2020-01-28 10:19 UTC, smashboy commented on src/redux/Actions/TableActions/generateTableAction.js
> +    });
так, індикатор того що іде якийсь процес

2020-01-28 10:20 UTC, smashboy commented on src/redux/keys.js
> +export const generateTableLoading = "generateTableLoading";
Інколи ще забуваю, вже виправив

2020-01-28 20:26 UTC, Shakhzadov approved these changes

2020-01-28 20:26 UTC, merged